version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - run: node --version  
   build2:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - run: aws --version
      
workflows:
  version: 2.1
  
  my_workflows:
    jobs:
      - build
      - build2
