
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:9.8.0-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run: docker build .
          #name: "Say hello world"
          #command: "echo Hello, World!"
     
#workflows:
 # build-deploy:
    #jobs:
     # - build
