version: 2.1

# jobs:
#   build:
#     docker:
#       - image: cimg/node:18.7.0
#     steps:
#       - checkout
#       - run: node --version  
#    build2:
#     docker:
#       - image: cimg/aws:2022.06
#     steps:
#       - checkout
#       - run: aws --version
      
# workflows:
#   version: 2.1
  
#   my_workflows:
#     jobs:
#       - build
#       - build2
      

  jobs:
    build:
      docker:
        - image: cimg/<language>:<version TAG>
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - checkout
        - run: <command>
    test:
      docker:
        - image: cimg/<language>:<version TAG>
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - checkout
        - run: <command>
  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test

