version: 2.1

workflow:
  test-deploy:
    jobs:
      - build
      - build2
jobs:
  build:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - run: node --version  
   build2:
    docker:
      - image: cimg/aws:2022.06
    steps:
      - checkout
      - run: aws --version
