jobs:
  build:
    docker:
      - image: cimg/node:18.7.0
    
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: node --version
  test:
    docker:
      - image: cimg/aws:2022.06
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: aws --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
