version: 2.1

workflows:
  test-environment:
    jobs:
      -test1
      
    jobs:
      test:
       docker:
          - image: cimg/node:18.4.0
        steps:
           - checkout
           - run: node --version
